# Generated by Django 5.2 on 2025-04-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confederation', models.CharField(choices=[('AFC', 'AFC'), ('CAF', 'CAF'), ('CONCACAF', 'CONCACAF'), ('CONMEBOL', 'CONMEBOL'), ('OFC', 'OFC'), ('UEFA', 'UEFA'), ('FIFA', 'FIFA')], max_length=10)),
                ('country', models.CharField(max_length=25)),
                ('competition_name', models.CharField(max_length=30)),
                ('competition_format', models.CharField(choices=[('L', 'League'), ('C', 'Cup'), ('H', 'Hybrid')], max_length=1)),
                ('competition_type', models.CharField(choices=[('D', 'Domestic'), ('I', 'International')], max_length=1)),
                ('season_start', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('season_end', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('event_data_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, max_length=1)),
                ('shot_data_available', models.BooleanField(choices=[(True, 'No'), (False, 'Yes')], default=False, max_length=1)),
            ],
        ),
    ]
